# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1747fa5730b8521fd3543948a093881f19101c603d9e3897e23ef14bf68425a63fde2a9a1d9b670685301ae4cef761d80a751025655f052abdc01abf4d31594

test:
  secret_key_base: 8b6de28f5ec6b3d3bb26c679d59350b9824bfcee4e8ee204afe8db3732b4236a5b92516a52c7df04b623156774dc42babab9c505eee78cbcc60b7d4ff25a8e9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
